services:

#----------------------------
# PostgreSQL (Primary Database)
#----------------------------
  postgres:
    image: postgres:15
    container_name: food-ordering-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - food-ordering-network
    restart: always


#----------------------------
# Elasticsearch
#----------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: food-ordering-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limit memory usage (important for dev!)
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - food-ordering-network
    restart: always

#----------------------------
# Kibana
#----------------------------
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: food-ordering-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://food-ordering-elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - food-ordering-network
    restart: always


volumes:
  postgres_data:
  elasticsearch_data:

networks:
  food-ordering-network:
    driver: bridge